Adding db scripts
Tshego-MM/beans_wechat pull request #5
Opened 2024-03-06 22:54 UTC by JoeKim-17

Adding Duncan's scripts, Something went wrong with the git histories in Duncan's branch

2024-03-07 05:21 UTC, sudosf approved these changes

2024-03-07 05:28 UTC, sudosf requested changes

2024-03-07 05:28 UTC, sudosf commented on Create_Statements.sql
> +UserLastName VARCHAR(1000) NULL,
Since it's the users table, i don't think we need to write it as "UserFirstName", "FIrstName" would just be fine, The Table "Users" already implies it (same with UserLastName)

2024-03-07 05:28 UTC, sudosf commented on Create_Statements.sql
> +EmailAddress NVARCHAR(500) NULL,
just a cosmetic recommendation, "Email' would work better i believe, long column names create room for spelling/mistype errors

2024-03-07 19:13 UTC, sudosf requested changes

2024-03-07 19:13 UTC, sudosf commented on Create_Statements.sql
> +USING WeChatBeansDB;
"USING" might present an error, i recommend "USE <DB_Name>"

2024-03-07 20:11 UTC, JoeKim-17 commented on Create_Statements.sql
> +USING WeChatBeansDB;
Noted and Completed

2024-03-08 07:51 UTC, sudosf requested changes

2024-03-08 07:51 UTC, sudosf commented on Constraints.sql
> +ADD CONSTRAINT UniqueEmailAddress UNIQUE (EmailAddress);
Hi @hleketaniDuncan97 , since Email column has been update,  i believe we should update the constraint name as well, else this statement will fail to execute

2024-03-08 11:33 UTC, closed without merging